services:
  router1:
    environment:
      - nome=roteador_1
      - ip=172.20.1.3
      - vizinhos={"roteador_4":["172.20.4.3",1],"roteador_2":["172.20.2.3",1]}
    build:
      context: ./router
      dockerfile: Dockerfile
    networks:
      subnet_4:
        ipv4_address: 172.20.4.2
      subnet_2:
        ipv4_address: 172.20.2.4
      subnet_1:
        ipv4_address: 172.20.1.3
    cap_add:
      - NET_ADMIN

  router2:
    environment:
      - nome=roteador_2
      - ip=172.20.2.3
      - vizinhos={"roteador_1":["172.20.1.3",1],"roteador_5":["172.20.5.3",1]}
    build:
      context: ./router
      dockerfile: Dockerfile
    networks:
      subnet_1:
        ipv4_address: 172.20.1.2
      subnet_5:
        ipv4_address: 172.20.5.4
      subnet_2:
        ipv4_address: 172.20.2.3
    cap_add:
      - NET_ADMIN

  router3:
    environment:
      - nome=roteador_3
      - ip=172.20.3.3
      - vizinhos={"roteador_6":["172.20.6.3",1],"roteador_5":["172.20.5.3",1]}
    build:
      context: ./router
      dockerfile: Dockerfile
    networks:
      subnet_6:
        ipv4_address: 172.20.6.2
      subnet_5:
        ipv4_address: 172.20.5.5
      subnet_3:
        ipv4_address: 172.20.3.3
    cap_add:
      - NET_ADMIN

  router4:
    environment:
      - nome=roteador_4
      - ip=172.20.4.3
      - vizinhos={"roteador_1":["172.20.1.3",1],"roteador_6":["172.20.6.3",1]}
    build:
      context: ./router
      dockerfile: Dockerfile
    networks:
      subnet_1:
        ipv4_address: 172.20.1.5
      subnet_6:
        ipv4_address: 172.20.6.4
      subnet_4:
        ipv4_address: 172.20.4.3
    cap_add:
      - NET_ADMIN

  router5:
    environment:
      - nome=roteador_5
      - ip=172.20.5.3
      - vizinhos={"roteador_2":["172.20.2.3",1],"roteador_6":["172.20.6.3",1], "roteador_3":["172.20.3.3",1]}
    build:
      context: ./router
      dockerfile: Dockerfile
    networks:
      subnet_2:
        ipv4_address: 172.20.2.2
      subnet_6:
        ipv4_address: 172.20.6.5
      subnet_3:
        ipv4_address: 172.20.3.4
      subnet_5:
        ipv4_address: 172.20.5.3
    cap_add:
      - NET_ADMIN

  router6:
    environment:
      - nome=roteador_6
      - ip=172.20.6.3
      - vizinhos={"roteador_5":["172.20.5.3",1],"roteador_3":["172.20.3.3",1], "roteador_4":["172.20.4.3",1]}
    build:
      context: ./router
      dockerfile: Dockerfile
    networks:
      subnet_5:
        ipv4_address: 172.20.5.2
      subnet_3:
        ipv4_address: 172.20.3.5
      subnet_4:
        ipv4_address: 172.20.4.4  
      subnet_6:
        ipv4_address: 172.20.6.3
    cap_add:
      - NET_ADMIN

  host1_1:
    environment:
      - ip=172.20.1.3
    build:
      context: ./host
      dockerfile: Dockerfile
    networks:
      subnet_1:
        ipv4_address: 172.20.1.11
    depends_on:
      - router1
    cap_add:
      - NET_ADMIN

  host1_2:
    environment:
      - ip=172.20.1.3
    build:
      context: ./host
      dockerfile: Dockerfile
    networks:
      subnet_1:
        ipv4_address: 172.20.1.12
    depends_on:
      - router1
    cap_add:
      - NET_ADMIN

  host2_1:
    environment:
      - ip=172.20.2.3
    build:
      context: ./host
      dockerfile: Dockerfile
    networks:
      subnet_2:
        ipv4_address: 172.20.2.11
    depends_on:
      - router2
    cap_add:
      - NET_ADMIN

  host2_2:
    environment:
      - ip=172.20.2.3
    build:
      context: ./host
      dockerfile: Dockerfile
    networks:
      subnet_2:
        ipv4_address: 172.20.2.12
    depends_on:
      - router2
    cap_add:
      - NET_ADMIN

  host3_1:
    environment:
      - ip=172.20.3.3
    build:
      context: ./host
      dockerfile: Dockerfile
    networks:
      subnet_3:
        ipv4_address: 172.20.3.11
    depends_on:
      - router3
    cap_add:
      - NET_ADMIN

  host3_2:
    environment:
      - ip=172.20.3.3
    build:
      context: ./host
      dockerfile: Dockerfile
    networks:
      subnet_3:
        ipv4_address: 172.20.3.12
    depends_on:
      - router3
    cap_add:
      - NET_ADMIN

  host4_1:
    environment:
      - ip=172.20.4.3
    build:
      context: ./host
      dockerfile: Dockerfile
    networks:
      subnet_4:
        ipv4_address: 172.20.4.11
    depends_on:
      - router4
    cap_add:
      - NET_ADMIN

  host4_2:
    environment:
      - ip=172.20.4.3
    build:
      context: ./host
      dockerfile: Dockerfile
    networks:
      subnet_4:
        ipv4_address: 172.20.4.12
    depends_on:
      - router4
    cap_add:
      - NET_ADMIN

  host5_1:
    environment:
      - ip=172.20.5.3
    build:
      context: ./host
      dockerfile: Dockerfile
    networks:
      subnet_5:
        ipv4_address: 172.20.5.11
    depends_on:
      - router5
    cap_add:
      - NET_ADMIN

  host5_2:
    environment:
      - ip=172.20.5.3
    build:
      context: ./host
      dockerfile: Dockerfile
    networks:
      subnet_5:
        ipv4_address: 172.20.5.12
    depends_on:
      - router5
    cap_add:
      - NET_ADMIN

  host6_1:
    environment:
      - ip=172.20.6.3
    build:
      context: ./host
      dockerfile: Dockerfile
    networks:
      subnet_6:
        ipv4_address: 172.20.6.11
    depends_on:
      - router6
    cap_add:
      - NET_ADMIN

  host6_2:
    environment:
      - ip=172.20.6.3
    build:
      context: ./host
      dockerfile: Dockerfile
    networks:
      subnet_6:
        ipv4_address: 172.20.6.12
    depends_on:
      - router6
    cap_add:
      - NET_ADMIN

networks:
  subnet_1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.1.0/24
          gateway: 172.20.1.1

  subnet_2:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.2.0/24
          gateway: 172.20.2.1

  subnet_3:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.3.0/24
          gateway: 172.20.3.1

  subnet_4:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.4.0/24
          gateway: 172.20.4.1

  subnet_5:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.5.0/24
          gateway: 172.20.5.1

  subnet_6:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.6.0/24
          gateway: 172.20.6.1
